import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin", 'cyrillic'],
});

const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-cormorant',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin", 'cyrillic'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",  // ← это важно для env(safe-area-inset-*)
};
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
